"""AI Market Brief generated by Claude via LangChain."""
import logging
from datetime import date
from typing import Any, Dict, List

from app.config import settings
from app.services.cache import cache_get, cache_set

logger = logging.getLogger(__name__)
CACHE_KEY = "portai:market:ai_brief"
CACHE_TTL = 3600  # 1 hour — Claude calls are expensive


async def generate_ai_brief(
    fear_greed: Dict[str, Any],
    indices: List[Dict[str, Any]],
    news: List[Dict[str, Any]],
) -> Dict[str, Any]:
    """Generate a concise AI market brief using Claude. Cached 1 hour."""
    cached = await cache_get(CACHE_KEY)
    if cached:
        return cached

    provider = settings.LLM_PROVIDER.lower()
    has_key = (
        (provider == "anthropic" and settings.ANTHROPIC_API_KEY) or
        (provider == "groq" and settings.GROQ_API_KEY) or
        (provider == "openai" and settings.OPENAI_API_KEY)
    )

    if not has_key:
        logger.warning("No LLM API key set for provider '%s' — returning mock brief", provider)
        result = _mock_brief()
        await cache_set(CACHE_KEY, result, ttl=CACHE_TTL)
        return result

    try:
        from langchain_core.messages import HumanMessage, SystemMessage

        if provider == "groq":
            from langchain_groq import ChatGroq
            llm = ChatGroq(
                model=settings.LLM_MODEL,
                api_key=settings.GROQ_API_KEY,
                temperature=0.3,
                max_tokens=600,
            )
        elif provider == "openai":
            from langchain_openai import ChatOpenAI
            llm = ChatOpenAI(
                model=settings.LLM_MODEL,
                api_key=settings.OPENAI_API_KEY,
                temperature=0.3,
                max_tokens=600,
            )
        else:  # anthropic (default)
            from langchain_anthropic import ChatAnthropic
            llm = ChatAnthropic(
                model=settings.LLM_MODEL,
                api_key=settings.ANTHROPIC_API_KEY,
                temperature=0.3,
                max_tokens=600,
            )

        indices_text = "\n".join(
            f"- {i['name']}: {_fmt_price(i['price'], i['currency'])} "
            f"({'+' if i['change_pct'] >= 0 else ''}{i['change_pct']:.2f}%)"
            for i in indices[:7]
        )
        headlines_text = "\n".join(f"- {n['title']}" for n in news[:5])
        today = date.today().strftime("%B %d, %Y")

        prompt = (
            f"Today is {today}.\n\n"
            f"Market Sentiment — Fear & Greed Index: {fear_greed['value']} "
            f"({fear_greed['classification']})\n\n"
            f"Major Indices & Prices:\n{indices_text}\n\n"
            f"Top Market Headlines:\n{headlines_text}\n\n"
            "Write a professional market brief (3–4 short paragraphs) for retail investors.\n"
            "• Para 1: overall market sentiment and key index moves\n"
            "• Para 2: cryptocurrency market summary\n"
            "• Para 3: key macro/news drivers\n"
            "• Final sentence: one actionable insight for a diversified portfolio investor\n"
            "Keep it factual, data-driven, and under 260 words."
        )

        messages = [
            SystemMessage(
                content="You are a professional financial market analyst. "
                        "Write clear, concise, factual daily market briefs."
            ),
            HumanMessage(content=prompt),
        ]
        response = await llm.ainvoke(messages)
        result = {
            "brief": response.content,
            "generated_at": date.today().isoformat(),
            "model": f"{provider}/{settings.LLM_MODEL}",
            "is_mock": False,
        }
    except Exception as exc:
        logger.error("AI brief generation failed: %s — using mock", exc)
        result = _mock_brief()

    await cache_set(CACHE_KEY, result, ttl=CACHE_TTL)
    return result


def _fmt_price(price: float, currency: str) -> str:
    if currency == "IDR":
        return f"Rp {price:,.0f}"
    return f"${price:,.2f}"


def _mock_brief() -> Dict[str, Any]:
    return {
        "brief": (
            "Global equity markets traded broadly higher, with the S&P 500 advancing 0.45% as "
            "technology stocks led gains. The NASDAQ Composite outperformed at +0.54%, while "
            "the Dow Jones Industrial Average posted a modest +0.15%. Indonesia's IDX Composite "
            "showed relative strength, gaining 0.75% on the back of foreign capital inflows into "
            "banking and commodity names.\n\n"
            "Cryptocurrency markets maintained their bullish tone. Bitcoin climbed 1.87% toward "
            "the $68,000 level, while Ethereum gained 1.20%. The Fear & Greed Index sits at 62 "
            "(Greed territory), suggesting continued positive momentum but warranting measured "
            "position sizing to guard against sharp reversals.\n\n"
            "On the macro front, Federal Reserve commentary continues to dominate. Sticky "
            "inflation data is pushing rate-cut expectations further out, creating headwinds for "
            "rate-sensitive sectors such as real estate and utilities. OPEC+ production discipline "
            "is providing a floor under oil prices, which in turn supports energy equities.\n\n"
            "For diversified investors: maintain balanced exposure across equities and crypto, "
            "while keeping a defensive allocation in gold or cash equivalents given the "
            "higher-for-longer rate environment."
        ),
        "generated_at": date.today().isoformat(),
        "model": "mock",
        "is_mock": True,
    }
