from datetime import datetime
from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field, model_validator


AssetClass = Literal["US_STOCKS", "IDX", "CRYPTO"]
RiskTolerance = Literal["conservative", "moderate", "aggressive"]
Horizon = Literal["1 month", "3 months", "6 months", "1 year", "3 years", "5 years"]


# ── Input ─────────────────────────────────────────────────────────────────────

class GeneratePortfolioRequest(BaseModel):
    budget: float = Field(gt=0, description="Total investment budget")
    currency: str = Field(default="USD", max_length=3)
    horizon: Horizon
    asset_classes: List[AssetClass] = Field(min_length=1)
    risk_tolerance: Optional[RiskTolerance] = None

    @model_validator(mode="after")
    def deduplicate_asset_classes(self) -> "GeneratePortfolioRequest":
        self.asset_classes = list(dict.fromkeys(self.asset_classes))
        return self


# ── Sub-models for report JSON ────────────────────────────────────────────────

class AllocationItem(BaseModel):
    asset_class: str
    percentage: float
    amount: float


class AssetItem(BaseModel):
    ticker: str
    name: str
    asset_class: str
    sector: Optional[str] = None
    allocation_percentage: float
    amount: float
    reasoning: str
    current_price: Optional[float] = None
    expected_return: Optional[str] = None


class RiskMetrics(BaseModel):
    expected_return: str
    risk_level: str
    max_drawdown_estimate: str
    sharpe_estimate: Optional[str] = None


class RebalancingInfo(BaseModel):
    suggested_date: Optional[str] = None
    trigger_conditions: List[str] = []


class PortfolioReport(BaseModel):
    summary: str
    total_budget: float
    currency: str
    horizon: str
    risk_profile: str
    allocation: List[AllocationItem]
    assets: List[AssetItem]
    risk_metrics: RiskMetrics
    rebalancing: RebalancingInfo
    market_context: str
    warnings: List[str] = []
    disclaimer: str = (
        "This report is generated by an AI system for educational purposes only. "
        "It does not constitute financial advice. Always consult a qualified financial "
        "advisor before making investment decisions."
    )


# ── Response models ────────────────────────────────────────────────────────────

class PortfolioResponse(BaseModel):
    id: int
    budget: float
    currency: str
    horizon: str
    asset_classes: List[str]
    risk_tolerance: Optional[str]
    allocation_plan: Optional[Dict[str, Any]]
    selected_assets: Optional[List[Dict[str, Any]]]
    report: Optional[Dict[str, Any]]
    status: str
    created_at: datetime
    completed_at: Optional[datetime]

    model_config = {"from_attributes": True}


class PortfolioListItem(BaseModel):
    id: int
    budget: float
    currency: str
    horizon: str
    status: str
    created_at: datetime

    model_config = {"from_attributes": True}
