"""Node 6 — REPORT_GENERATOR: LLM produces the final professional portfolio report."""
import json
import logging
from datetime import date, timedelta

from langchain_core.messages import HumanMessage, SystemMessage

from app.agents.llm import build_llm
from app.agents.state import PortfolioState

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "This report is generated by an AI system (PortAI) for educational and simulation purposes only. "
    "It does not constitute financial advice, an investment recommendation, or a solicitation to buy or "
    "sell any financial instrument. Past performance is not indicative of future results. Always consult "
    "a qualified financial advisor before making investment decisions."
)



SYSTEM_PROMPT = """You are a senior portfolio manager writing a professional investment report.
Write clearly, analytically, and educationally. The report is for simulation/educational purposes.

Return ONLY valid JSON (no markdown fences) in this exact schema:
{
  "summary": "<2-3 sentence executive summary>",
  "risk_metrics": {
    "expected_return": "<e.g. 8-12% annually>",
    "risk_level": "<Low | Moderate | High>",
    "max_drawdown_estimate": "<e.g. -15%>",
    "sharpe_estimate": "<e.g. 1.2>"
  },
  "rebalancing": {
    "suggested_date": "<YYYY-MM-DD>",
    "trigger_conditions": ["<condition 1>", "<condition 2>"]
  },
  "market_context": "<1-2 paragraph market overview relevant to this portfolio>",
  "warnings": ["<risk warning 1>", "<risk warning 2>"]
}

The assets list and allocation breakdown will be merged in by the system — do NOT include them."""


async def report_generator_node(state: PortfolioState) -> PortfolioState:
    user_input = state["user_input"]
    allocation_plan = state["allocation_plan"]
    selected_assets = state["selected_assets"]
    risk = state.get("inferred_risk", "moderate")
    errors: list[str] = list(state.get("errors", []))

    assets_summary = json.dumps(selected_assets, default=str)

    prompt = f"""
Portfolio details:
- Budget: {user_input.budget} {user_input.currency}
- Horizon: {user_input.horizon}
- Risk profile: {risk}
- Asset classes: {user_input.asset_classes}

Allocation plan:
{json.dumps(allocation_plan, indent=2)}

Selected assets:
{assets_summary}

Generate the report JSON now.
"""

    try:
        llm = build_llm(max_tokens=4096)
        response = await llm.ainvoke([
            SystemMessage(content=SYSTEM_PROMPT),
            HumanMessage(content=prompt),
        ])
        raw = response.content.strip()
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
        llm_output: dict = json.loads(raw)
    except Exception as exc:
        logger.error("ReportGenerator LLM call failed: %s — using fallback", exc)
        errors.append(f"Report generator used fallback due to: {exc}")
        llm_output = _fallback_llm_output(user_input.horizon)

    # Build the full report by merging LLM output with structured data
    allocation_list = [
        {
            "asset_class": ac,
            "percentage": float(info["percentage"]),
            "amount": float(info["amount"]),
        }
        for ac, info in allocation_plan.items()
    ]

    report = {
        "summary": llm_output.get("summary", "Portfolio generated by PortAI."),
        "total_budget": float(user_input.budget),
        "currency": user_input.currency,
        "horizon": user_input.horizon,
        "risk_profile": risk,
        "allocation": allocation_list,
        "assets": selected_assets,
        "risk_metrics": llm_output.get("risk_metrics", {
            "expected_return": "N/A",
            "risk_level": risk.capitalize(),
            "max_drawdown_estimate": "N/A",
            "sharpe_estimate": "N/A",
        }),
        "rebalancing": llm_output.get("rebalancing", {
            "suggested_date": str(date.today() + timedelta(days=90)),
            "trigger_conditions": ["Significant market correction (>10%)", "Portfolio drift > 5%"],
        }),
        "market_context": llm_output.get("market_context", ""),
        "warnings": llm_output.get("warnings", []),
        "disclaimer": DISCLAIMER,
    }

    logger.info("ReportGenerator: report built successfully")
    return {**state, "report": report, "errors": errors}


def _fallback_llm_output(horizon: str) -> dict:
    return {
        "summary": (
            "This portfolio is constructed based on your investment preferences and current market data. "
            "It is diversified across selected asset classes to balance risk and return."
        ),
        "risk_metrics": {
            "expected_return": "8-12% annually",
            "risk_level": "Moderate",
            "max_drawdown_estimate": "-20%",
            "sharpe_estimate": "1.0",
        },
        "rebalancing": {
            "suggested_date": str(date.today() + timedelta(days=90)),
            "trigger_conditions": [
                "If any asset gains or loses more than 20% from entry price",
                "At the end of the stated investment horizon",
            ],
        },
        "market_context": (
            "Global markets are navigating a period of monetary policy normalisation. "
            "Investors should remain diversified and monitor central bank communications."
        ),
        "warnings": [
            "Cryptocurrency assets are highly volatile and may lose significant value.",
            "Past performance does not guarantee future results.",
        ],
    }
