"""add_fundamental_analysis_tables

Revision ID: 2a7c2f1c1507
Revises: edf92076b6b7
Create Date: 2026-05-18 21:06:03.856927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2a7c2f1c1507'
down_revision: Union[str, None] = 'edf92076b6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fundamental_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('normalized_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ratios', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trend_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('red_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('valuation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entry_signal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('narrative_report', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='fundamental_status'), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fundamental_analyses_id'), 'fundamental_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_fundamental_analyses_ticker'), 'fundamental_analyses', ['ticker'], unique=False)
    op.create_index(op.f('ix_fundamental_analyses_user_id'), 'fundamental_analyses', ['user_id'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('file_type', sa.Enum('pdf', 'xlsx', name='file_type_enum'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['fundamental_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_files_analysis_id'), 'uploaded_files', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_id'), 'uploaded_files', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_files_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_analysis_id'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index(op.f('ix_fundamental_analyses_user_id'), table_name='fundamental_analyses')
    op.drop_index(op.f('ix_fundamental_analyses_ticker'), table_name='fundamental_analyses')
    op.drop_index(op.f('ix_fundamental_analyses_id'), table_name='fundamental_analyses')
    op.drop_table('fundamental_analyses')
    # ### end Alembic commands ###
